// Catalog Collection
export const products = [
  // New collection (compressed images)
  {
    id: '1',
    name: 'Small Dish',
    category: 'Decor',
    price: 28,
    image: '/images/DSCF4494.jpg',
    imageAlt: 'Small shallow dish with soft grey-blue glaze and natural brown clay showing through.',
    description: 'Small shallow dish/trinket tray; soft grey-blue glaze; organic marbled effect.',
    details: 'A small shallow dish or trinket tray, approximately 8cm in diameter, with a soft grey-blue glaze and natural brown clay showing through for an organic marbled effect. Gentle sloped sides, hand-thrown with visible texture—perfect for jewelry, keys, or as a decorative accent. Contemporary rustic with a Japanese-inspired aesthetic.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['2', '3'],
  },
  {
    id: '2',
    name: 'Small Bud Vase',
    category: 'Decor',
    price: 38,
    image: '/images/DSCF4499.jpg',
    image2: '/images/DSCF4505.jpg',
    image3: '/images/DSCF4506.jpg',
    image4: '/images/DSCF4507.jpg',
    imageAlt: 'Miniature rounded bud vase with dual-toned glaze.',
    image2Alt: 'Small bud vase showing warm brown and pale grey-blue glaze.',
    image3Alt: 'Bud vase with narrow neck and spherical body.',
    image4Alt: 'Handmade bud vase with subtle irregularities.',
    description: 'Miniature rounded vase; dual-toned brown and grey-blue; wabi-sabi aesthetic.',
    details: 'A miniature rounded vase, approximately 6–7cm tall, with a dual-toned finish: warm brown upper portion transitioning to pale grey-blue, and an exposed terracotta clay band at the base. Small narrow neck opening and spherical body, handmade with subtle irregularities that add character. Minimalist wabi-sabi aesthetic—perfect for a single stem or as a standalone decorative object.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['1', '3'],
  },
  {
    id: '3',
    name: 'Medium Serving Bowl – Patchwork Glaze',
    category: 'Dining',
    price: 58,
    image: '/images/DSCF4512.jpg',
    image2: '/images/DSCF4516.jpg',
    image3: '/images/DSCF4518.jpg',
    image4: '/images/DSCF4520.jpg',
    imageAlt: 'Medium serving bowl with cream, white and chocolate brown glaze sections.',
    image2Alt: 'Patchwork glaze bowl showing wide, generous form.',
    image3Alt: 'Serving bowl with smooth interior and tactile exterior.',
    image4Alt: 'Bold contemporary bowl with artisanal craftsmanship.',
    description: 'Medium serving/display bowl; three-section cream, white and chocolate brown glaze.',
    details: 'A medium serving or display bowl, approximately 18–20cm in diameter, with a distinctive three-section color block of cream, white, and rich chocolate brown glazes. Wide, generous form with gently rounded sides, smooth interior and tactile exterior. Bold contemporary design with artisanal craftsmanship—ideal for salads, fruit, or as a statement centerpiece.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['4', '5'],
  },
  {
    id: '4',
    name: 'Pair of Medium Bowls – Marbled Finish',
    category: 'Dining',
    price: 52,
    image: '/images/DSCF4524.jpg',
    image2: '/images/DSCF4526.jpg',
    imageAlt: 'Pair of nesting bowls with organic marbled cream and brown glaze.',
    image2Alt: 'Companion bowls with unique individual glazing patterns.',
    description: 'Set of two nesting bowls; organic marbled cream and brown; hand-thrown.',
    details: 'A set of two nesting or companion bowls, approximately 15–17cm diameter each, with an organic marbled pattern in cream and warm brown tones creating natural flowing designs. Similar forms with unique individual glazing patterns and visible wheel marks. Organic, nature-inspired aesthetic—perfect for serving, food prep, or display as a coordinated pair.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['3', '5'],
  },
  {
    id: '5',
    name: 'Large Serving Bowl – Carved Texture',
    category: 'Dining',
    price: 68,
    image: '/images/DSCF4540.jpg',
    image2: '/images/DSCF4545.jpg',
    image3: '/images/DSCF4547.jpg',
    imageAlt: 'Large serving bowl with hand-carved geometric pattern and rich brown interior.',
    image2Alt: 'Carved texture bowl with glossy interior and matte exterior.',
    image3Alt: 'Sculptural centerpiece bowl with blue-grey accents.',
    description: 'Large decorative serving bowl; carved linear texture; rich brown and blue-grey.',
    details: 'A large decorative serving bowl, approximately 22–25cm in diameter, with a rich brown interior and hand-carved linear texture around the exterior rim with subtle blue-grey accents. Wide, shallow form with a distinctive hand-carved geometric pattern creating rhythmic texture; glossy interior contrasts with matte carved exterior. Contemporary artisanal with architectural detail—a statement piece for serving, fruit display, or as a sculptural centerpiece. The carved detailing makes each piece unique and catches light beautifully from different angles.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['3', '4'],
  },
  // Original collection
  {
    id: '6',
    name: 'Modular Pour-Over Set',
    category: 'Coffee',
    price: 85,
    image: '/images/L1008197.JPG',
    image2: '/images/L1008201.JPG',
    imageAlt: 'Two-piece modular pour-over set with sage green and cream split-glaze finish in matte.',
    image2Alt: 'Modular ceramic pour-over set showing sage green and cream split-glaze transition.',
    description: 'Two-piece modular set; sage green/cream split glaze; matte finish.',
    details: 'A two-piece modular pour-over set featuring a sage green and cream split-glaze finish with a matte surface. The modular design allows for flexible use, with the dripper and carafe working together seamlessly. The split-glaze creates a distinctive visual transition while maintaining the functional elegance of the pour-over method.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['7'],
  },
  {
    id: '7',
    name: 'Signature Split-Glaze Mug',
    category: 'Coffee',
    price: 38,
    image: '/images/L1008209.JPG',
    image2: '/images/L1008208.JPG',
    imageAlt: 'Hand-thrown signature split-glaze mug with ergonomic handle matching the pour-over aesthetic.',
    image2Alt: 'Signature split-glaze mug showing ergonomic handle and matching glaze finish.',
    description: 'Hand-thrown; matching pour-over aesthetic; ergonomic handle.',
    details: 'A hand-thrown mug featuring a signature split-glaze design that matches the pour-over set aesthetic. The ergonomic handle is designed for comfortable daily use, while the glaze transition creates visual interest. Perfect for pairing with the Modular Pour-Over Set.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['6'],
  },
  {
    id: '8',
    name: 'Wave-Etched Bud Vase',
    category: 'Decor',
    price: 32,
    image: '/images/L1008228.JPG',
    image2: '/images/L1008229.JPG',
    imageAlt: 'Ochre clay bud vase with hand-carved horizontal wave patterns and rustic texture.',
    image2Alt: 'Wave-etched bud vase showing hand-carved horizontal waves in ochre clay.',
    description: 'Ochre clay; hand-carved horizontal waves; rustic texture.',
    details: 'A bud vase in ochre clay featuring hand-carved horizontal wave patterns that wrap around the form. The carving creates texture and visual movement, while the rustic finish emphasizes the handmade character. Each piece is unique, with variations in the wave patterns.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['9', '10'],
  },
  {
    id: '9',
    name: 'Crazed Amber Bud Vase',
    category: 'Decor',
    price: 38,
    image: '/images/DSC05732.JPG',
    image2: '/images/DSC05727.JPG',
    imageAlt: 'High-gloss amber bud vase with intentional crackle glaze finish in warm amber tone.',
    image2Alt: 'Crazed amber bud vase showing intentional crackle glaze texture and warm amber tone.',
    description: 'High-gloss finish; intentional crackle glaze; warm amber tone.',
    details: 'A bud vase featuring a high-gloss finish with an intentional crackle glaze that creates fine lines throughout the surface. The warm amber tone catches light beautifully, while the crackling adds depth and character. The glossy finish emphasizes the refined aesthetic.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['8', '10'],
  },
  {
    id: '10',
    name: 'Speckled Moon Vase',
    category: 'Decor',
    price: 48,
    image: '/images/DSCF4399.JPG',
    image2: '/images/DSCF4410.JPG',
    imageAlt: 'Speckled moon vase showing spherical form with heavy iron speckling.',
    image2Alt: 'Small spherical bud vase with sage green and cream glaze and heavy iron speckling.',
    description: 'Small spherical bud vase; sage green and cream glaze; heavy iron speckling.',
    details: 'A small, spherical bud vase featuring a sage green and cream glaze with heavy iron speckling throughout. The round form creates a calm, moon-like presence, while the speckling adds texture and visual interest. The intimate scale makes it perfect for single stems or small arrangements.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['8', '9'],
  },
  {
    id: '11',
    name: 'Sand-Tone Breakfast Bowl',
    category: 'Dining',
    price: 32,
    image: '/images/L1008175.JPG',
    image2: '/images/L1008177.JPG',
    imageAlt: 'Breakfast bowl with speckled stone finish, iron spotting, and versatile deep form.',
    image2Alt: 'Sand-tone breakfast bowl showing iron spotting and deep versatile form.',
    description: 'Speckled stone finish; iron spotting; versatile deep form.',
    details: 'A breakfast bowl finished in a speckled stone glaze with natural iron spotting throughout. The deep, versatile form is perfect for everyday meals, from cereal to soup. The texture and color variations create a natural, earthy appearance that brings warmth to the table.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['3', '4'],
  },
]
