// Catalog Collection
export const products = [
  // Coffee
  {
    id: '1',
    name: 'Signature Mug',
    category: 'Coffee',
    price: 38,
    image: '/images/L1008267.JPG',
    image2: '/images/L1008271.JPG',
    imageAlt: 'Hand-thrown ceramic mug with warm split glaze and soft ergonomic handle.',
    image2Alt: 'Signature split-glaze mug showing ergonomic handle and everyday coffee scale.',
    description: 'Hand-thrown; warm split glaze; soft ergonomic handle; everyday coffee scale.',
    details: 'A hand-thrown mug featuring a warm split-glaze finish with a soft, ergonomic handle designed for comfortable daily use. The glaze transition creates visual interest while the form emphasizes functionality and everyday utility.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['2', '3'],
  },
  {
    id: '2',
    name: 'Small Coffee Cup',
    category: 'Coffee',
    price: 32,
    image: '/images/L1008274.JPG',
    image2: '/images/L1008277.JPG',
    imageAlt: 'Low-profile ceramic coffee cup with comfortable lip and tactile satin glaze.',
    image2Alt: 'Small coffee cup showing intimate scale and satin glaze finish.',
    description: 'Low-profile form; comfortable lip; tactile satin glaze; intimate scale.',
    details: 'A small, low-profile coffee cup designed for intimate daily moments. The comfortable lip and tactile satin glaze finish make it a pleasure to hold and use. The form emphasizes simplicity and quiet elegance.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['1', '3'],
  },
  {
    id: '3',
    name: 'Ceramic Pourer',
    category: 'Coffee',
    price: 42,
    image: '/images/L1008263.JPG',
    image2: '/images/L1008264.JPG',
    imageAlt: 'Ceramic pourer with integrated spout and controlled pour design.',
    image2Alt: 'Soft silhouette ceramic pourer showing domestic profile and integrated spout.',
    description: 'Integrated spout; controlled pour; soft silhouette; domestic profile.',
    details: 'A functional ceramic pourer with an integrated spout designed for controlled pouring. The soft silhouette and domestic profile make it a beautiful addition to any kitchen, combining form and function seamlessly.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['1', '2'],
  },
  // Dining
  {
    id: '4',
    name: 'Breakfast Bowl',
    category: 'Dining',
    price: 36,
    image: '/images/DSC05722.JPG',
    image2: '/images/DSC05723.JPG',
    imageAlt: 'Open form breakfast bowl with generous depth and speckled stoneware finish.',
    image2Alt: 'Breakfast bowl showing everyday utility and speckled stoneware texture.',
    description: 'Open form; generous depth; speckled stoneware; everyday utility.',
    details: 'An open-form breakfast bowl with generous depth, perfect for everyday meals. The speckled stoneware finish adds texture and visual interest while maintaining the practical utility needed for daily use.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['5', '6'],
  },
  {
    id: '5',
    name: 'Low Bowl',
    category: 'Dining',
    price: 48,
    image: '/images/DSC05727.JPG',
    image2: '/images/DSC05728.JPG',
    imageAlt: 'Low bowl with calm continuous curve and versatile size.',
    image2Alt: 'Low bowl showing warm interior glaze and unglazed foot ring.',
    description: 'Calm continuous curve; versatile size; warm interior glaze; unglazed foot ring.',
    details: 'A low bowl featuring a calm, continuous curve that creates a versatile form suitable for various uses. The warm interior glaze contrasts beautifully with the unglazed foot ring, adding visual depth and tactile interest.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['4', '6'],
  },
  {
    id: '6',
    name: 'Dinner Plate',
    category: 'Dining',
    price: 44,
    image: '/images/DSC05710.JPG',
    image2: '/images/DSC05713.JPG',
    imageAlt: 'Dinner plate with shallow profile and soft rim.',
    image2Alt: 'Durable stoneware dinner plate showing subtle glaze break.',
    description: 'Shallow profile; soft rim; durable stoneware; subtle glaze break.',
    details: 'A refined dinner plate with a shallow profile and soft rim, designed for both everyday use and special occasions. The durable stoneware construction and subtle glaze break create a piece that is both beautiful and functional.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['4', '5'],
  },
  // Decor
  {
    id: '7',
    name: 'Bud Vase',
    category: 'Decor',
    price: 40,
    image: '/images/L1008250.JPG',
    image2: '/images/L1008256.JPG',
    imageAlt: 'Small rounded bud vase with quiet silhouette and subtle sculptural presence.',
    image2Alt: 'Bud vase showing rounded form and subtle sculptural details.',
    description: 'Small rounded form; quiet silhouette; subtle sculptural presence.',
    details: 'A small, rounded bud vase with a quiet silhouette that brings subtle sculptural presence to any space. The form emphasizes simplicity and elegance, making it perfect for single stems or small arrangements.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['8', '9'],
  },
  {
    id: '8',
    name: 'Rounded Vase (Small)',
    category: 'Decor',
    price: 55,
    image: '/images/L1008259.JPG',
    image2: '/images/L1008260.JPG',
    imageAlt: 'Small rounded vase with soft bulb form and warm tonal glaze.',
    image2Alt: 'Rounded vase showing calm domestic object and warm glaze finish.',
    description: 'Soft bulb form; warm tonal glaze; calm domestic object.',
    details: 'A small rounded vase featuring a soft bulb form and warm tonal glaze. The calm, domestic presence makes it a beautiful addition to any interior, bringing natural warmth and organic form to the space.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['7', '9'],
  },
  {
    id: '9',
    name: 'Rounded Vase (Medium)',
    category: 'Decor',
    price: 68,
    image: '/images/L1008261.JPG',
    image2: '/images/L1008262.JPG',
    imageAlt: 'Medium rounded vase with proportional sculptural form and subtle glaze variation.',
    image2Alt: 'Rounded vase showing handmade character and glaze variation.',
    description: 'Proportional sculptural form; subtle glaze variation; handmade character.',
    details: 'A medium-sized rounded vase with a proportional sculptural form that showcases subtle glaze variation and handmade character. The form demonstrates technical skill while maintaining the organic, one-of-a-kind quality of hand-thrown ceramics.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['7', '8'],
  },
]
