// Signature Collection - Curated launch collection
export const products = [
  // Coffee
  {
    id: '1',
    name: 'Pour-Over Set (Dripper + Base)',
    category: 'Coffee',
    price: 85,
    image: '/images/L1008197.jpg',
    image2: '/images/L1008201.jpg',
    imageAlt: 'Handmade ceramic coffee pour-over set with funnel dripper and carafe in a matte sage green and cream split-glaze finish.',
    image2Alt: 'Artisan ceramic coffee dripper and cylindrical carafe showing the vertical split-glaze transition between earth-toned green and speckled white.',
    description: 'Modular pour-over set demonstrating technical skill and design',
    details: 'A complete pour-over coffee set featuring green and cream split-glaze finishes. This hero product showcases technical skill with its modular design—the carafe and dripper funnel work together seamlessly for the perfect pour-over experience. The glaze transitions create visual interest while maintaining functionality.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['2'], // Links to Signature Split-Glaze Mug
  },
  {
    id: '2',
    name: 'Signature Split-Glaze Mug',
    category: 'Coffee',
    price: 38,
    image: '/images/L1008209.jpg',
    image2: '/images/L1008208.jpg',
    imageAlt: 'Close-up of a hand-thrown ceramic mug in sage green glaze, grouped with a matching coffee carafe and pour-over dripper.',
    image2Alt: 'Hand-thrown ceramic mug in sage green and cream split-glaze finish.',
    description: 'Hand-thrown mug with distinctive split-glaze finish',
    details: 'A hand-thrown mug featuring a signature split-glaze design. The green and cream glaze transition creates a unique, one-of-a-kind appearance. Perfect for daily use, this mug showcases the technical skill of split-glaze application. Shares the same glaze and aesthetic as the Pour-Over Set.',
    material: 'Stoneware',
    process: 'Hand-thrown',
    relatedProducts: ['1'], // Links to Pour-Over Set
  },
  // Decor
  {
    id: '3',
    name: 'Wave-Etched Bud Vase',
    category: 'Decor',
    price: 52,
    image: '/images/L1008228.jpg',
    image2: '/images/L1008229.jpg',
    imageAlt: 'Squat bud vase in toasted ochre clay featuring hand-etched horizontal wave patterns and a narrow rim.',
    image2Alt: 'Hand-etched wave pattern bud vase in toasted ochre clay, side view.',
    description: 'Squat vase with hand-etched wave patterns',
    details: 'A substantial bud vase featuring hand-etched wave patterns that wrap around the form. The etching creates texture and visual movement, making each piece unique. Part of the Earth & Iron Series, emphasizing organic, wabi-sabi aesthetics.',
    material: 'Stoneware',
    process: 'Hand-thrown',
  },
  {
    id: '4',
    name: 'Crazed Amber Bud Vase',
    category: 'Decor',
    price: 45,
    image: '/images/DSC05732.JPG',
    image2: '/images/DSC05727.JPG',
    imageAlt: 'High-gloss amber ceramic bud vase with a specialized crazed crackle glaze finish on a wooden tabletop.',
    image2Alt: 'Close-up detail of crazed crackle glaze texture on amber ceramic bud vase.',
    description: 'High-gloss amber vase with fine crazing',
    details: 'A high-gloss amber bud vase with fine crazing (crackled glaze texture) throughout. The glossy finish catches light beautifully, while the crazing adds character and depth to the surface. Part of the refined Amber Gloss Collection.',
    material: 'Stoneware',
    process: 'Hand-thrown',
  },
  // Dining
  {
    id: '5',
    name: 'Amber Dinner Plate',
    category: 'Dining',
    price: 42,
    image: '/images/DSC05710.JPG',
    image2: '/images/DSC05713.JPG',
    imageAlt: 'Coordinated amber glazed dinner set featuring a dinner plate and shallow bowl on a white marble surface.',
    image2Alt: 'Amber glazed dinner plate with shallow bowl, close-up view.',
    description: 'High-gloss amber dinner plate',
    details: 'A refined dinner plate featuring a high-gloss amber glaze. Part of the Amber Gloss Collection, this plate works beautifully for elevated dining occasions while remaining functional for everyday use.',
    material: 'Stoneware',
    process: 'Hand-thrown',
  },
  {
    id: '6',
    name: 'Sand-Tone Breakfast Bowl',
    category: 'Dining',
    price: 32,
    image: '/images/L1008175.jpg',
    image2: '/images/L1008177.jpg',
    imageAlt: 'Deep ceramic breakfast bowl in a speckled sand-tone glaze with natural iron spotting and flared rim.',
    image2Alt: 'Sand-tone breakfast bowl with natural iron spotting, interior view.',
    description: 'Deep stone-colored bowl with natural iron spotting',
    details: 'A deep, substantial breakfast bowl finished in a warm sand-tone glaze with natural iron spotting throughout. The texture and color variations create a natural, earthy appearance. Part of the Earth & Iron Series, perfect for those seeking organic, wabi-sabi styles.',
    material: 'Stoneware',
    process: 'Hand-thrown',
  },
  // Kitchen
  {
    id: '7',
    name: 'Artisan Oil Cruet',
    category: 'Kitchen',
    price: 55,
    image: '/images/DSCF4413.JPG',
    image2: '/images/DSCF4479.JPG',
    imageAlt: 'Forest green kitchenware set including a sculptural oil cruet with metal spout, pitcher, and candle holder.',
    image2Alt: 'Forest green artisan oil cruet with metal spout, detailed view.',
    description: 'Hollow-form oil cruet with metal spout in deep forest green',
    details: 'A unique hollow-form oil cruet with a metal spout, finished in deep forest green glaze. This piece highlights one of the most distinctive functional forms, showcasing both technical skill and design innovation. Part of the Artisan Kitchen Set.',
    material: 'Stoneware',
    process: 'Hand-thrown',
  },
]
